version: '2'

services:

  age_service:
    image: hoeghh/age:1.0
    ports:
      # The metrics port for the age service
      - 8892:8080

  name_service:
    image: hoeghh/name:1.0
    ports:
      # The metrics port for the name service
      - 8893:8080

  sentence_service:
    image: hoeghh/sentence:1.0
    command: /sentence -age-service http://age_service:8080 -name-service http://name_service:8080
    ports:
      # The metrics and main application port
      - 8890:8080
