apiVersion: "autoscaling.k8s.io/v1beta2"
kind: VerticalPodAutoscaler
metadata:
  name: sentences
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: sentences
  updatePolicy:
    # "Auto" means both on POD creation and update of existing PODs
    updateMode: "Auto"
