apiVersion: "autoscaling.k8s.io/v1beta2"
kind: VerticalPodAutoscaler
metadata:
  name: sentence
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: sentence
  resourcePolicy:
    containerPolicies:
      - containerName: "*"
        minAllowed:
          memory: 300Mi
        maxAllowed:
          memory: 1Gi
  updatePolicy:
    # "Auto" means both on POD creation and update of existing PODs
    updateMode: "Auto"
