apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: loadgen
  name: loadgen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadgen
  template:
    metadata:
      labels:
        app: loadgen
    spec:
      containers:
      - image: praqma/network-multitool
        name: multitool
        command: ['ab', '-n', '100000000', '-c', '10', 'http://sentences:5000/']
        resources:
          limits:
            cpu: 0.5
          requests:
            cpu: 0.5
