rbac:
  create: false
serviceAccounts:
  server:
    create: false
    name: user-x-sa
alertmanager:
  enabled: false
pushgateway:
  enabled: false
networkPolicy:
  enabled: false
nodeExporter:
  enabled: false
kubeStateMetrics:
  enabled: false
server:
  retention: '1d'
  resources:
    limits:
      cpu: 250m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  service:
    type: NodePort