rbac:
  create: false
alertmanager:
  enabled: false
pushgateway:
  enabled: false
networkPolicy:
  enabled: false
nodeExporter:
  enabled: false
kubeStateMetrics:
  enabled: false
server:
  retention: '1d'
