sidecar:
  dashboards:
    enabled: true
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: prometheus
      type: prometheus
      access: proxy
      url: http://prometheus-server:80
      isDefault: true
      editable: false
service:
  type: LoadBalancer
  port: 80
rbac:
  namespaced: true
  pspEnabled: false
  pspUseAppArmor: false
resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 2550m
    memory: 128Mi
