apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sentences
    component: main
  name: sentences
spec:
  selector:
    matchLabels:
      app: sentences
      component: main
  template:
    metadata:
      labels:
        app: sentences
        component: main
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8000'
    spec:
      #priorityClassName: medium-priority
      containers:
      - image: praqma/sentences-app:latest
        imagePullPolicy: IfNotPresent
        name: sentences
        args: ['--mode', 'sentence',
          '--age-service', 'http://sentence-age:5000',
          '--name-service', 'http://sentence-name:5000'
	]
        resources:
          requests:
            cpu: 0.25
          limits:
            cpu: 0.25
