apiVersion: v1
kind: Service
metadata:
  labels:
    app: sentences
    component: name
  name: sentence-name
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: sentences
    component: name
  type: ClusterIP
