apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sentences
    component: name
  name: sentence-name
spec:
  selector:
    matchLabels:
      app: sentences
      component: name
  template:
    metadata:
      labels:
        app: sentences
        component: name
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8000'
    spec:
      #priorityClassName: medium-priority
      containers:
      - image: praqma/sentences-app:latest
        imagePullPolicy: IfNotPresent
        name: sentences
        args: ['--mode', 'name']
        resources:
          requests:
            cpu: 0.25
          limits:
            cpu: 0.25
