apiVersion: v1
kind: Service
metadata:
  labels:
    app: sentences
    component: age
  name: sentence-age
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: sentences
    component: age
  type: ClusterIP
