apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sentences
  name: sentences
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentences
  template:
    metadata:
      labels:
        app: sentences
    spec:
      containers:
      - image: sentences:latest
        imagePullPolicy: IfNotPresent
        name: sentences
        args: ['--mode', 'sentence',
          '--age-service', 'http://sentence-age:5000',
          '--name-service', 'http://sentence-name:5000'
	]
        resources:
          requests:
            cpu: 0.5
          limits:
            cpu: 0.5
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sentences
  name: sentences
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: sentences
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sentence-name
  name: sentence-name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentence-name
  template:
    metadata:
      labels:
        app: sentence-name
    spec:
      containers:
      - image: sentences:latest
        imagePullPolicy: IfNotPresent
        name: sentences
        args: ['--mode', 'name']
        resources:
          requests:
            cpu: 0.5
          limits:
            cpu: 0.5
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sentence-name
  name: sentence-name
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: sentence-name
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sentence-age
  name: sentence-age
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentence-age
  template:
    metadata:
      labels:
        app: sentence-age
    spec:
      containers:
      - image: sentences:latest
        imagePullPolicy: IfNotPresent
        name: sentences
        args: ['--mode', 'age']
        resources:
          requests:
            cpu: 0.5
          limits:
            cpu: 0.5
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sentence-age
  name: sentence-age
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: sentence-age
  type: ClusterIP
