apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sentences
    component: age
  name: sentence-age
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentences
      component: age
  template:
    metadata:
      labels:
        app: sentences
        component: age
    spec:
      #priorityClassName: medium-priority
      containers:
      - image: praqma/sentences-app:latest
        imagePullPolicy: IfNotPresent
        name: sentences
        args: ['--mode', 'age']
        resources:
          requests:
            cpu: 0.25
          limits:
            cpu: 0.25
