apiVersion: v1
kind: Service
metadata:
  labels:
    app: sentences
  name: sentences-metrics
  annotations:
    prometheus.io/scrape: 'true'
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: sentences
  type: ClusterIP
