apiVersion: v1
kind: Service
metadata:
  labels:
    app: sentences
  name: sentences
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: sentences
  type: ClusterIP
